# Generated by Django 5.1.1 on 2024-09-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=123, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=123, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('password', models.CharField(max_length=128)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('description', models.TextField(blank=True, null=True, verbose_name='о себе')),
                ('phone_number', models.CharField(max_length=17, verbose_name='Номер телефона')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar_img/')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('qr_code_img', models.ImageField(blank=True, null=True, upload_to='tour_qr_codes/', verbose_name='QR code для оплаты')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Обычный пользователь'), (2, 'Менеджер'), (3, 'Консультант'), (4, 'Автор тура')], default=1, verbose_name='Статус пользователя')),
                ('is_author', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
